LABELS_PATH = "./model/data/coco.names"
YOLOV3_CFG_PATH = "./model/data/config/yolov3.cfg"
YOLOV3_WEIGHTS_PATH = "./model/data/weights/yolov3.weights"
YOLOV3_TINY_CFG_PATH = "./model/data/config/yolov3-tiny.cfg"
YOLOV3_TINY_WEIGHTS_PATH = "./model/data/weights/yolov3-tiny.weights"